enum Status {
  NONE = 'NONE',
  SHORT = 'SHORT',
  LONG = 'LONG',
  DOUBLE = 'DOUBLE',
  HIT_LONG_ENTRY = 'HIT_LONG_ENTRY',
  HIT_LONG_ENTRY_1 = 'HIT_LONG_ENTRY_1',
  HIT_LONG_ENTRY_2 = 'HIT_LONG_ENTRY_2',
  HIT_LONG_ENTRY_3 = 'HIT_LONG_ENTRY_3',
  HIT_SHORT_ENTRY = 'HIT_SHORT_ENTRY',
  HIT_SHORT_ENTRY_1 = 'HIT_SHORT_ENTRY_1',
  HIT_SHORT_ENTRY_2 = 'HIT_SHORT_ENTRY_2',
  HIT_SHORT_ENTRY_3 = 'HIT_SHORT_ENTRY_3',
  HIT_LONG_CLOSE = 'HIT_LONG_CLOSE',
  HIT_SHORT_CLOSE = 'HIT_SHORT_CLOSE',
  GET_LONG_ENTRY = 'GET_LONG_ENTRY',
  GET_SHORT_ENTRY = 'GET_SHORT_ENTRY',
  GET_LONG_CLOSE = 'GET_LONG_CLOSE',
  GET_SHORT_CLOSE = 'GET_SHORT_CLOSE',
  GET_LONG_LIQUIDATION = 'GET_LONG_LIQUIDATION',
  GET_SHORT_LIQUIDATION = 'GET_SHORT_LIQUIDATION',
}

export default Status
