export enum ValidationDirection {
  NONE = "NONE",
  SHORT = "SHORT",
  LONG = "LONG",
  DOUBLE = "DOUBLE",
  HIT_LONG_ENTRY = "HIT_LONG_ENTRY",
  HIT_LONG_ENTRY_1 = "HIT_LONG_ENTRY_1",
  HIT_LONG_ENTRY_2 = "HIT_LONG_ENTRY_2",
  HIT_LONG_ENTRY_3 = "HIT_LONG_ENTRY_3",
  HIT_SHORT_ENTRY = "HIT_SHORT_ENTRY",
  HIT_SHORT_ENTRY_1 = "HIT_SHORT_ENTRY_1",
  HIT_SHORT_ENTRY_2 = "HIT_SHORT_ENTRY_2",
  HIT_SHORT_ENTRY_3 = "HIT_SHORT_ENTRY_3",
  HIT_LONG_CLOSE = "HIT_LONG_CLOSE",
  HIT_SHORT_CLOSE = "HIT_SHORT_CLOSE",
  GET_LONG_ENTRY = "GET_LONG_ENTRY",
  GET_LONG_ENTRY_1 = "GET_LONG_ENTRY_1",
  GET_LONG_ENTRY_2 = "GET_LONG_ENTRY_2",
  GET_LONG_ENTRY_3 = "GET_LONG_ENTRY_3",
  GET_SHORT_ENTRY = "GET_SHORT_ENTRY",
  GET_SHORT_ENTRY_1 = "GET_SHORT_ENTRY_1",
  GET_SHORT_ENTRY_2 = "GET_SHORT_ENTRY_2",
  GET_SHORT_ENTRY_3 = "GET_SHORT_ENTRY_3",
  GET_LONG_CLOSE = "GET_LONG_CLOSE",
  GET_SHORT_CLOSE = "GET_SHORT_CLOSE",
}

export enum ZoneStatus {
  NONE = "NONE",
  ENTRY = "ENTRY",
  CLOSED = "CLOSED",
}

export const ValidationDirectionEntries = [
  ValidationDirection.HIT_LONG_ENTRY_1,
  ValidationDirection.HIT_LONG_ENTRY_2,
  ValidationDirection.HIT_LONG_ENTRY_3,
  ValidationDirection.HIT_SHORT_ENTRY_1,
  ValidationDirection.HIT_SHORT_ENTRY_2,
  ValidationDirection.HIT_SHORT_ENTRY_3,
];
