import crypto from 'crypto'

// List of temporary email providers to block
const TEMPORARY_EMAIL_PROVIDERS = [
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'mailinator.com',
  'tempmail.net',
  'yopmail.com',
  'temp-mail.org',
  'getairmail.com',
  'throwaway.email',
  'maildrop.cc',
  'mohmal.com',
  'mailnesia.com',
  'dispostable.com',
  'tempail.com',
  'sharklasers.com',
  'grr.la',
  'guerrillamailblock.com',
  'pokemail.net',
  'spam4.me',
  'trbvm.com',
  'trashmail.com',
  'mt2014.com',
  'mailtemp.info',
  'tempinbox.com',
  'mytemp.email',
  'tempemail.net',
  'emailondeck.com',
  'fake-box.com',
  'tempemailaddress.com',
  'mvrht.com',
  'vusra.com',
  'lroid.com',
  'uroid.com',
  'troid.com',
  'groid.com',
  'broid.com',
  'croid.com',
  'droid.com',
  'froid.com',
  'hroid.com',
  'jroid.com',
  'kroid.com',
  'nroid.com',
  'proid.com',
  'qroid.com',
  'rroid.com',
  'sroid.com',
  'wroid.com',
  'xroid.com',
  'yroid.com',
  'zroid.com',
  'armyspy.com',
  'cuvox.de',
  'dayrep.com',
  'einrot.com',
  'fleckens.hu',
  'gustr.com',
  'jourrapide.com',
  'rhyta.com',
  'superrito.com',
  'teleworm.us',
  'noopener.com',
  'protonmail.com',
  'tutanota.com',
  'protonmail.ch',
  'tutanota.de',
  'cock.li',
  'protonmail.com',
  'pm.me',
  'tuta.io',
  'tutamail.com',
  'keemail.me',
  'secmail.pro',
  'secmail.pro',
  'scryptmail.com',
  'torbox3uiot6wchz.onion',
  'freemail.ms',
  'tmail.ws',
  'tmailweb.com',
  'tmails.net',
  'tmailo.com',
  'tmailr.com',
  'tmailbox.org',
  'tmailweb.net',
  'zetmail.com',
  'zetmail.org',
  'tmail.com',
  'nada.email',
  'email-fake.com',
  'getnada.com',
  'mailhog.example',
  'mailtrap.io',
  'ethereal.email',
  'restmail.net',
  'putsbox.com',
  'mailsac.com',
  'inbox.testmail.app',
  'temp-mail.io',
  'mail.tm',
  'inboxkitten.com',
  'emaildrop.io',
  'internxt.com',
  'cryptogmail.com',
  'criptext.com',
  'scryptmail.com',
  'ctemplar.com',
  'startmail.com',
  'mailfence.com',
  'runbox.com',
  'posteo.de',
  'mailbox.org',
  'kolab.com',
  'fastmail.com',
  'yahoo.com',
  'outlook.com',
  'hotmail.com',
  'aol.com',
  'icloud.com',
  'me.com',
  'mac.com',
  'live.com',
  'msn.com',
  'skype.com',
  'gmail.com',
  'googlemail.com',
  'qq.com',
  '163.com',
  '126.com',
  'yeah.net',
  'sina.com',
  'sohu.com',
  'aliyun.com',
  'alibaba.com',
  'taobao.com',
  'tmall.com',
  '1688.com',
  'alimama.com',
  'yandex.com',
  'yandex.ru',
  'mail.ru',
  'rambler.ru',
  'list.ru',
  'bk.ru',
  'inbox.ru',
  'internet.ru',
  'ngs.ru',
  'sibmail.com',
  'ufanet.ru',
  'yandex.kz',
  'yandex.ua',
  'yandex.by',
  'yandex.az',
  'yandex.am',
  'yandex.ge',
  'yandex.kg',
  'yandex.lt',
  'yandex.lv',
  'yandex.md',
  'yandex.tj',
  'yandex.tm',
  'yandex.uz',
  'yandex.ee',
  'yandex.fr',
  'yandex.com.tr',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
  'yandex.com.ua',
  'yandex.com.kz',
  'yandex.com.by',
  'yandex.com.az',
  'yandex.com.tj',
  'yandex.com.uz',
  'yandex.com.kg',
  'yandex.com.md',
  'yandex.com.tm',
  'yandex.com.ee',
  'yandex.com.lv',
  'yandex.com.lt',
  'yandex.com.am',
  'yandex.com.ge',
  'yandex.co.il',
]

// Simplified list of most common temporary email providers
const TEMP_EMAIL_DOMAINS = [
  '10minutemail.com',
  'guerrillamail.com',
  'mailinator.com',
  'tempmail.net',
  'yopmail.com',
  'temp-mail.org',
  'getairmail.com',
  'throwaway.email',
  'maildrop.cc',
  'mohmal.com',
  'mailnesia.com',
  'dispostable.com',
  'tempail.com',
  'sharklasers.com',
  'grr.la',
  'trashmail.com',
  'tempemailaddress.com',
  'emailondeck.com',
  'fake-box.com',
  'nada.email',
  'mail.tm',
  'inboxkitten.com',
  'emaildrop.io',
  'mailsac.com',
  'restmail.net',
  'putsbox.com',
  'tempinbox.com',
  'mytemp.email',
  'tempemail.net',
  'mailtemp.info',
  'mt2014.com',
  'trbvm.com',
  'spam4.me',
  'mvrht.com',
  'vusra.com',
  'lroid.com',
  'uroid.com',
  'troid.com',
  'groid.com',
  'broid.com',
  'croid.com',
  'droid.com',
  'froid.com',
  'hroid.com',
  'jroid.com',
  'kroid.com',
  'nroid.com',
  'proid.com',
  'qroid.com',
  'rroid.com',
  'sroid.com',
  'wroid.com',
  'xroid.com',
  'yroid.com',
  'zroid.com',
  'armyspy.com',
  'cuvox.de',
  'dayrep.com',
  'einrot.com',
  'fleckens.hu',
  'gustr.com',
  'jourrapide.com',
  'rhyta.com',
  'superrito.com',
  'teleworm.us',
  'noopener.com',
  'cock.li',
  'freemail.ms',
  'tmail.ws',
  'tmailweb.com',
  'tmails.net',
  'tmailo.com',
  'tmailr.com',
  'tmailbox.org',
  'tmailweb.net',
  'zetmail.com',
  'zetmail.org',
  'tmail.com',
  'email-fake.com',
  'getnada.com',
  'temp-mail.io',
  'inbox.testmail.app',
  'mailtrap.io',
  'ethereal.email',
  'mailhog.example'
]

export function isValidEmail(email: string): boolean {
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
  return emailRegex.test(email)
}

export function isTemporaryEmail(email: string): boolean {
  const domain = email.toLowerCase().split('@')[1]
  return TEMP_EMAIL_DOMAINS.includes(domain)
}

export function hasGmailPlusAlias(email: string): boolean {
  const lowercaseEmail = email.toLowerCase()
  const domain = lowercaseEmail.split('@')[1]
  const localPart = lowercaseEmail.split('@')[0]
  
  // Check if it's a Gmail domain and contains a plus sign
  const gmailDomains = ['gmail.com', 'googlemail.com']
  return gmailDomains.includes(domain) && localPart.includes('+')
}

export function normalizeEmail(email: string): string {
  const lowercaseEmail = email.toLowerCase()
  const [localPart, domain] = lowercaseEmail.split('@')
  
  // For Gmail, remove dots and plus aliases
  if (domain === 'gmail.com' || domain === 'googlemail.com') {
    const cleanLocal = localPart.replace(/\./g, '').split('+')[0]
    return `${cleanLocal}@gmail.com`
  }
  
  return lowercaseEmail
}

export function generateEmailVerificationToken(): string {
  return crypto.randomBytes(32).toString('hex')
}

export function validateEmailForRegistration(email: string): {
  isValid: boolean
  error?: string
} {
  // Basic email format validation
  if (!isValidEmail(email)) {
    return { isValid: false, error: 'Invalid email format' }
  }

  // Check for temporary email providers
  if (isTemporaryEmail(email)) {
    return { isValid: false, error: 'Temporary email addresses are not allowed' }
  }

  // Check for Gmail plus aliases
  if (hasGmailPlusAlias(email)) {
    return { isValid: false, error: 'Gmail plus aliases are not allowed' }
  }

  return { isValid: true }
}

export function isTrialExpired(trialEndDate: Date): boolean {
  return new Date() > trialEndDate
}

export function getTrialTimeRemaining(trialEndDate: Date): {
  expired: boolean
  minutes: number
  seconds: number
} {
  const now = new Date()
  const timeRemaining = trialEndDate.getTime() - now.getTime()
  
  if (timeRemaining <= 0) {
    return { expired: true, minutes: 0, seconds: 0 }
  }
  
  const minutes = Math.floor(timeRemaining / (1000 * 60))
  const seconds = Math.floor((timeRemaining % (1000 * 60)) / 1000)
  
  return { expired: false, minutes, seconds }
}
